# Site settings
title: javaindepth
email: rakeshr.21@gmail.com
description: The idea of the blog is to understand and discuss java in depth and various functionality Happy coding :)  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: javaindepth
github_username:  javaindepth

# Build settings
markdown: kramdown
